archives:
  - id: provider
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    builds:
    - provider
  - id: arm2pulumi
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    builds:
    - arm2pulumi
before:
  hooks:
    - make init_submodules
    - make codegen
    - make generate_schema
blobs:
  - bucket: get.pulumi.com
    folder: releases/plugins/
    ids:
      - provider # Only provider archive should be pushed to get.pulumi.com
    provider: s3
    region: us-west-2
builds:
  - binary: pulumi-resource-azure-native
    id: provider
    dir: provider
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/pulumi/pulumi-azure-native/provider/pkg/version.Version={{.Tag}}
    main: ./cmd/pulumi-resource-azure-native/
  - binary: arm2pulumi
    id: arm2pulumi
    dir: provider
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/pulumi/pulumi-azure-native/provider/pkg/version.Version={{.Tag}}
    main: ./cmd/arm2pulumi

changelog:
  skip: true
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
